global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'jaeger-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['jaeger:14269']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']